import Head from 'next/head';
import { useRouter } from 'next/router';

// components
import Dashboard from '../components/Dashboard';
import Spinner from '../components/Spinner';

// nextAuth
import { useSession } from 'next-auth/react';

export default function Home() {
  const router = useRouter();
  const { status, data: session } = useSession({
    required: true,
    onUnauthenticated() {
      router.push('/auth/signin');
    },
  });

  if (status === 'loading') return <Spinner />;
  return (
    <div className="">
      <Head>
        <title>Dashboard - Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </div>
  );
}
