import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spotify - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
